import { Buffer } from 'node:buffer';
import { BitStream } from 'bit-buffer';

// * This exists solely because I really like the API of binary-parser, however it has 2 major issues:
// *
// * 1. It does not natively support encoding. There is a PR for this https://github.com/keichi/binary-parser/pull/243
// *    however it has had no activity in 2 years and shows no signs of being merged.
// *
// * 2. It, and some other binary parsing libraries I tried like struct-fu, seem to have weird issues where they can't
// *    handle some Mii data? I genuinely have no idea why. I found that bit-buffer can handle it fine though, so I decided
// *    to just build a binary-parser style API around it. See https://gist.github.com/jonbarrow/aa4f448cc2a3fa4f1f49721ad3c93f1c
// *    for an example of this issue.
// *
// * Plus this adds in many helpful additions like bit skipping, more type safety, a Zod-like interface, etc.

// TODO - Remove all the "unknown"/"any" usage? Seems kinda smelly
// TODO - Support nested structures? We don't need it right now but might be nice to have

// * This will "prettify" the types generated by the BinaryParser method chaining.
// * In an example like:
// *
// * const parser = new BinaryParser()
// * 	.int32le('little')
// * 	.int32be('big');
// *
// * const parsed = parser.parse(Buffer.from([ 0x4e, 0x61, 0xbc, 0x00, 0x00, 0xbc, 0x61, 0x4e ]));
// *
// * "parsed" will be typed as:
// *
// * const parsed: Record<string, any> & {
// *     little: number;
// * } & {
// *     big: number;
// * }
// *
// * "Prettify" turns this into:
// *
// * const parsed: {
// *     little: number;
// *     big: number;
// * }
type Prettify<T> = {
	[K in keyof T]: T[K];
} & {}; // eslint-disable-line @typescript-eslint/ban-types

type CommandType =
	| { type: 'set_endianness'; endianness: 'big' | 'little'; }
	| { type: 'check_min'; value: number; }
	| { type: 'check_max'; value: number; }
	| { type: 'check_range'; min: number; max: number; }
	| { type: 'custom_validate'; callback: (parsed: any) => void; } // eslint-disable-line @typescript-eslint/no-explicit-any
	| { type: 'skip'; bits: number; }
	| BitsFieldCommand
	| BooleanBitFieldCommand
	| IntFieldCommand
	| BufferFieldCommand
	| StringFieldCommand;

type NumberFieldOptions = {
	min?: number;
	max?: number;
};

type BufferFieldOptions = {
	length: number;
};

type StringFieldOptions = {
	length: number;
	encoding: BufferEncoding;
};

class BitsFieldCommand {
	public readonly type = 'bits';
	public name: string;
	public options?: NumberFieldOptions;
	public bits: number;

	constructor(settings: { name: string; options?: NumberFieldOptions, bits: number; }) {
		this.name = settings.name;
		this.options = settings.options;
		this.bits = settings.bits;
	}

	parse(stream: BitStream): number {
		return stream.readBits(this.bits);
	}

	encode(stream: BitStream, parsed: Record<string, unknown>): void {
		stream.writeBits(parsed[this.name] as number, this.bits);
	}
}

class BooleanBitFieldCommand {
	public readonly type = 'boolean_bit';
	public readonly bits = 1;
	public name: string;

	constructor(settings: { name: string; }) {
		this.name = settings.name;
	}

	parse(stream: BitStream): boolean {
		return !!stream.readBits(1);
	}

	encode(stream: BitStream, parsed: Record<string, unknown>): void {
		stream.writeBits(parsed[this.name] ? 1 : 0, 1);
	}
}

class IntFieldCommand {
	public readonly type = 'int';
	public name: string;
	public signed: boolean;
	public endianness: 'current' | 'big' | 'little';
	public options?: NumberFieldOptions;
	public bits: 8 | 16 | 32;

	constructor(settings: { name: string; signed: boolean; endianness?: 'current' | 'big' | 'little'; options?: NumberFieldOptions; bits: 8 | 16 | 32; }) {
		this.name = settings.name;
		this.signed = settings.signed;
		this.endianness = settings.endianness || 'current'; // * Only not set for 8 bit numbers, so this doesn't matter
		this.options = settings.options;
		this.bits = settings.bits;
	}

	parse(stream: BitStream): number {
		const currentEndianness = stream.bigEndian;
		let value: number;

		if (this.bits !== 8 && this.endianness !== 'current') {
			stream.bigEndian = this.endianness === 'big' ? true : false;
		}

		if (this.signed) {
			value = this.bits === 8 ? stream.readInt8() : this.bits === 16 ? stream.readInt16() : stream.readInt32();
		} else {
			value = this.bits === 8 ? stream.readUint8() : this.bits === 16 ? stream.readUint16() : stream.readUint32();
		}

		stream.bigEndian = currentEndianness;

		return value;
	}

	encode(stream: BitStream, parsed: Record<string, unknown>): void {
		const currentEndianness = stream.bigEndian;

		if (this.bits !== 8 && this.endianness !== 'current') {
			stream.bigEndian = this.endianness === 'big' ? true : false;
		}

		const value = parsed[this.name] as number;

		if (this.signed) {
			this.bits === 8 ? stream.writeInt8(value) : this.bits === 16 ? stream.writeInt16(value) : stream.writeInt32(value);
		} else {
			this.bits === 8 ? stream.writeUint8(value) : this.bits === 16 ? stream.writeUint16(value) : stream.writeUint32(value);
		}

		stream.bigEndian = currentEndianness;
	}
}

class BufferFieldCommand {
	public readonly type = 'buffer';
	public name: string;
	public options: BufferFieldOptions;
	public bits: number;

	constructor(settings: { name: string; options: BufferFieldOptions; bits: number; }) {
		this.name = settings.name;
		this.options = settings.options;
		this.bits = settings.bits;
	}

	parse(stream: BitStream): Buffer {
		return Buffer.from(stream.readArrayBuffer(this.options.length));
	}

	encode(stream: BitStream, parsed: Record<string, unknown>): void {
		(parsed[this.name] as Buffer).forEach(byte => stream.writeUint8(byte));
	}
}

class StringFieldCommand {
	public readonly type = 'string';
	public name: string;
	public options: StringFieldOptions;
	public bits: number;

	constructor(settings: { name: string; options: StringFieldOptions; bits: number; }) {
		this.name = settings.name;
		this.options = settings.options;
		this.bits = settings.bits;
	}

	parse(stream: BitStream): string {
		return Buffer.from(stream.readArrayBuffer(this.options.length)).toString(this.options.encoding);
	}

	encode(stream: BitStream, parsed: Record<string, unknown>): void {
		const stringBuffer = Buffer.from(parsed[this.name] as string, this.options.encoding);
		const terminatedBuffer = Buffer.alloc(this.options.length);

		terminatedBuffer.set(stringBuffer);
		terminatedBuffer.forEach(byte => stream.writeUint8(byte));
	}
}

/**
 * Custom structure parser with an API aimed at matching `binary-parser`, with additions. Uses `bit-buffer` under the hood
 */
export default class BinaryParser<T extends object = Record<never, never>> { // eslint-disable-line @typescript-eslint/no-explicit-any
	private commands: CommandType[] = [];

	/**
	 * Zod-like `z.infer` method, Do not call at runtime. Use `ReturnType<typeof BinaryParser.infer<typeof parser>>`
	 */
	static infer<TParser extends BinaryParser<any>>(_parser: TParser): TParser extends BinaryParser<infer U> ? Prettify<U> : never { // eslint-disable-line @typescript-eslint/no-explicit-any
		throw new Error('This method is only for type inference and should never be called at runtime.');
	}

	/**
	 * Sets the endianness for all values moving forward. Parser is big-endian by default
	 *
	 * @param endianness - The new endianness
	 * @returns The current `BinaryParser` instance
	 */
	public endianness(endianness: 'big' | 'little'): this {
		this.commands.push({
			type: 'set_endianness',
			endianness: endianness
		});

		return this;
	}

	/**
	 * Alias of `bitN`
	 *
	 * @param name - The name of the decoded field
	 * @param bits - The number of bits to read
	 * @returns The current `BinaryParser` instance
	 */
	public bits<K extends string>(name: K, bits: number, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, bits, options);
	}

	/**
	 * Reads `bits` number of bits
	 *
	 * @param name - The name of the decoded field
	 * @param bits - The number of bits to read
	 * @returns The current `BinaryParser` instance
	 */
	public bitN<K extends string>(name: K, bits: number, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		this.commands.push(new BitsFieldCommand({
			name: name,
			...(options && { options }),
			bits: bits
		}));

		return this as unknown as BinaryParser<T & { [P in K]: number }>;
	}

	/**
	 * Reads a single bit, interpreted as a boolean
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public booleanBit<K extends string>(name: K): BinaryParser<T & { [P in K]: boolean }> {
		this.commands.push(new BooleanBitFieldCommand({
			name: name
		}));

		return this as unknown as BinaryParser<T & { [P in K]: boolean }>;
	}

	/**
	 * Alias of `bit1`
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit<K extends string>(name: K): BinaryParser<T & { [P in K]: number }> {
		return this.bit1(name);
	}

	/**
	 * Reads a single bit
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit1<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 1, options);
	}

	/**
	 * Reads 2 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit2<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 2, options);
	}

	/**
	 * Reads 3 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit3<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 3, options);
	}

	/**
	 * Reads 4 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit4<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 4, options);
	}

	/**
	 * Reads 5 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit5<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 5, options);
	}

	/**
	 * Reads 6 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit6<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 6, options);
	}

	/**
	 * Reads 7 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit7<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 7, options);
	}

	/**
	 * Reads 8 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit8<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 8, options);
	}

	/**
	 * Reads 9 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit9<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 9, options);
	}

	/**
	 * Reads 10 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit10<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 10, options);
	}

	/**
	 * Reads 11 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit11<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 11, options);
	}

	/**
	 * Reads 12 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit12<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 12, options);
	}

	/**
	 * Reads 13 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit13<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 13, options);
	}

	/**
	 * Reads 14 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit14<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 14, options);
	}

	/**
	 * Reads 15 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit15<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 15, options);
	}

	/**
	 * Reads 16 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit16<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 16, options);
	}

	/**
	 * Reads 17 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit17<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 17, options);
	}

	/**
	 * Reads 18 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit18<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 18, options);
	}

	/**
	 * Reads 19 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit19<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 19, options);
	}

	/**
	 * Reads 20 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit20<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 20, options);
	}

	/**
	 * Reads 21 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit21<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 21, options);
	}

	/**
	 * Reads 22 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit22<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 22, options);
	}

	/**
	 * Reads 23 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit23<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 23, options);
	}

	/**
	 * Reads 24 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit24<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 24, options);
	}

	/**
	 * Reads 25 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit25<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 25, options);
	}

	/**
	 * Reads 26 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit26<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 26, options);
	}

	/**
	 * Reads 27 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit27<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 27, options);
	}

	/**
	 * Reads 28 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit28<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 28, options);
	}

	/**
	 * Reads 29 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit29<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 29, options);
	}

	/**
	 * Reads 30 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit30<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 30, options);
	}

	/**
	 * Reads 31 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit31<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 31, options);
	}

	/**
	 * Reads 32 bits
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public bit32<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		return this.bitN(name, 32, options);
	}

	/**
	 * Reads an unsigned 8-bit integer
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public uint8<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		this.commands.push(new IntFieldCommand({
			name: name,
			signed: false,
			...(options && { options }),
			bits: 8
		}));

		return this as unknown as BinaryParser<T & { [P in K]: number }>;
	}

	/**
	 * Reads a signed 8-bit integer
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public int8<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		this.commands.push(new IntFieldCommand({
			name: name,
			signed: true,
			...(options && { options }),
			bits: 8
		}));

		return this as unknown as BinaryParser<T & { [P in K]: number }>;
	}

	/**
	 * Reads an unsigned 16-bit integer using the currently set endianness
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public uint16<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		this.commands.push(new IntFieldCommand({
			name: name,
			signed: false,
			endianness: 'current',
			...(options && { options }),
			bits: 16
		}));

		return this as unknown as BinaryParser<T & { [P in K]: number }>;
	}

	/**
	 * Reads an unsigned 16-bit integer in little-endian mode, regardless of the currently set endianness
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public uint16le<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		this.commands.push(new IntFieldCommand({
			name: name,
			signed: false,
			endianness: 'little',
			...(options && { options }),
			bits: 16
		}));

		return this as unknown as BinaryParser<T & { [P in K]: number }>;
	}

	/**
	 * Reads an unsigned 16-bit integer in big-endian mode, regardless of the currently set endianness
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public uint16be<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		this.commands.push(new IntFieldCommand({
			name: name,
			signed: false,
			endianness: 'big',
			...(options && { options }),
			bits: 16
		}));

		return this as unknown as BinaryParser<T & { [P in K]: number }>;
	}

	/**
	 * Reads a signed 16-bit integer using the currently set endianness
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public int16<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		this.commands.push(new IntFieldCommand({
			name: name,
			signed: true,
			endianness: 'current',
			...(options && { options }),
			bits: 16
		}));

		return this as unknown as BinaryParser<T & { [P in K]: number }>;
	}

	/**
	 * Reads a signed 16-bit integer in little-endian mode, regardless of the currently set endianness
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public int16le<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		this.commands.push(new IntFieldCommand({
			name: name,
			signed: true,
			endianness: 'little',
			...(options && { options }),
			bits: 16
		}));

		return this as unknown as BinaryParser<T & { [P in K]: number }>;
	}

	/**
	 * Reads a signed 16-bit integer in big-endian mode, regardless of the currently set endianness
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public int16be<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		this.commands.push(new IntFieldCommand({
			name: name,
			signed: true,
			endianness: 'big',
			...(options && { options }),
			bits: 16
		}));

		return this as unknown as BinaryParser<T & { [P in K]: number }>;
	}

	/**
	 * Reads an unsigned 32-bit integer using the currently set endianness
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public uint32<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		this.commands.push(new IntFieldCommand({
			name: name,
			signed: false,
			endianness: 'current',
			...(options && { options }),
			bits: 32
		}));

		return this as unknown as BinaryParser<T & { [P in K]: number }>;
	}

	/**
	 * Reads an unsigned 32-bit integer in little-endian mode, regardless of the currently set endianness
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public uint32le<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		this.commands.push(new IntFieldCommand({
			name: name,
			signed: false,
			endianness: 'little',
			...(options && { options }),
			bits: 32
		}));

		return this as unknown as BinaryParser<T & { [P in K]: number }>;
	}

	/**
	 * Reads an unsigned 32-bit integer in big-endian mode, regardless of the currently set endianness
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public uint32be<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		this.commands.push(new IntFieldCommand({
			name: name,
			signed: false,
			endianness: 'big',
			...(options && { options }),
			bits: 32
		}));

		return this as unknown as BinaryParser<T & { [P in K]: number }>;
	}

	/**
	 * Reads a signed 32-bit integer using the currently set endianness
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public int32<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		this.commands.push(new IntFieldCommand({
			name: name,
			signed: true,
			endianness: 'current',
			...(options && { options }),
			bits: 32
		}));

		return this as unknown as BinaryParser<T & { [P in K]: number }>;
	}

	/**
	 * Reads a signed 32-bit integer in little-endian mode, regardless of the currently set endianness
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public int32le<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		this.commands.push(new IntFieldCommand({
			name: name,
			signed: true,
			endianness: 'little',
			...(options && { options }),
			bits: 32
		}));

		return this as unknown as BinaryParser<T & { [P in K]: number }>;
	}

	/**
	 * Reads a signed 32-bit integer in big-endian mode, regardless of the currently set endianness
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public int32be<K extends string>(name: K, options?: NumberFieldOptions): BinaryParser<T & { [P in K]: number }> {
		this.commands.push(new IntFieldCommand({
			name: name,
			signed: true,
			endianness: 'big',
			...(options && { options }),
			bits: 32
		}));

		return this as unknown as BinaryParser<T & { [P in K]: number }>;
	}

	/**
	 * Skips `length` bytes. When encoding, skipped bytes are set to null
	 *
	 * @param length - The number of bytes to skip
	 * @returns The current `BinaryParser` instance
	 */
	public skip(length: number): this {
		return this.skipBits(length * 8);
	}

	/**
	 * Skips `length` bits. When encoding, skipped bits are set to 0
	 *
	 * @param length - The number of bits to skip
	 * @returns The current `BinaryParser` instance
	 */
	public skipBits(length: number): this {
		this.commands.push({
			type: 'skip',
			bits: length
		});

		return this;
	}

	/**
	 * Reads a `Buffer` of data of size `options.length`
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public buffer<K extends string>(name: K, options: BufferFieldOptions): BinaryParser<T & { [P in K]: Buffer }> {
		this.commands.push(new BufferFieldCommand({
			name: name,
			options: options,
			bits: options.length * 8
		}));

		return this as unknown as BinaryParser<T & { [P in K]: Buffer }>;
	}

	/**
	 * Reads a string of data of size `options.length` in `options.encoding` encoding
	 *
	 * @param name - The name of the decoded field
	 * @returns The current `BinaryParser` instance
	 */
	public string<K extends string>(name: K, options: StringFieldOptions): BinaryParser<T & { [P in K]: string }> {
		this.commands.push(new StringFieldCommand({
			name: name,
			options: options,
			bits: options.length * 8
		}));

		return this as unknown as BinaryParser<T & { [P in K]: string }>;
	}

	/**
	 * Ensures the parsed value is greater than, or equal to, the provided value. Can also be set using `options.min`
	 * when parsing a number
	 *
	 * @param value - Minimum value
	 * @returns The current `BinaryParser` instance
	 */
	public min(value: number): this {
		this.commands.push({
			type: 'check_min',
			value: value
		});

		return this;
	}

	/**
	 * Ensures the parsed value is less than, or equal to, the provided value. Can also be set using `options.max`
	 * when parsing a number
	 *
	 * @param value - Maximum value
	 * @returns The current `BinaryParser` instance
	 */
	public max(value: number): this {
		this.commands.push({
			type: 'check_max',
			value: value
		});

		return this;
	}

	/**
	 * Ensures the parsed value is the given range, inclusive. Can also be set using both `options.min` and
	 * `options.max` when parsing a number
	 *
	 * @param min - Minimum value
	 * @param max - Maximum value
	 * @returns The current `BinaryParser` instance
	 */
	public range(min: number, max: number): this {
		this.commands.push({
			type: 'check_range',
			min: min,
			max: max
		});

		return this;
	}

	/**
	 * Defines a custom validation function. Can be used for complex checks across multiple fields. Expected
	 * to throw errors when found
	 *
	 * @param callback - Custom validation function
	 * @returns The current `BinaryParser` instance
	 */
	public validate(callback: (parsed: T) => void): this {
		this.commands.push({
			type: 'custom_validate',
			callback: callback
		});

		return this;
	}

	/**
	 * Uses the current structure to parse `data`. Will throw any errors that occur
	 *
	 * @param data - Raw binary data to parse with the current structure
	 * @returns Object of parsed data
	 */
	public parse(data: Buffer): Prettify<T> {
		const stream = new BitStream(data.buffer as ArrayBuffer, data.byteOffset, data.byteLength); // TODO - Can this "as" be removed?
		const result: Record<string, unknown> = {};
		let latestField: {
			name: string;
			value: unknown;
		} | undefined = undefined;

		stream.bigEndian = true; // * Make this match binary-parser, BE by default

		for (const command of this.commands) {
			if (command.type === 'set_endianness') {
				stream.bigEndian = command.endianness === 'big' ? true : false;
			}

			if (command.type === 'skip') {
				stream.index += command.bits;
				continue;
			}

			if (command.type === 'custom_validate') {
				command.callback(result as T);
				continue;
			}

			if (command.type === 'check_min' && latestField) {
				if (latestField.value as number < command.value) {
					throw new Error(`Field '${latestField.name}' is invalid. Value ${latestField.value} is less than ${command.value}`);
				}

				continue;
			}

			if (command.type === 'check_max' && latestField) {
				if (latestField.value as number > command.value) {
					throw new Error(`Field '${latestField.name}' is invalid. Value ${latestField.value} is greater than ${command.value}`);
				}

				continue;
			}

			if (command.type === 'check_range' && latestField) {
				if (latestField.value as number < command.min) {
					throw new Error(`Field '${latestField.name}' is invalid. Value ${latestField.value} is less than ${command.min}`);
				}

				if (latestField.value as number > command.max) {
					throw new Error(`Field '${latestField.name}' is invalid. Value ${latestField.value} is greater than ${command.max}`);
				}

				continue;
			}

			if ('name' in command) {
				const value = command.parse(stream);

				if ('options' in command && command.options && 'min' in command.options) {
					if (value as number < command.options.min!) {
						throw new Error(`Field '${command.name}' is invalid. Value ${value} is less than ${command.options.min!}`);
					}
				}

				if ('options' in command && command.options && 'max' in command.options) {
					if (value as number > command.options.max!) {
						throw new Error(`Field '${command.name}' is invalid. Value ${value} is greater than ${command.options.max!}`);
					}
				}

				result[command.name] = value;
				latestField = {
					name: command.name,
					value: value
				};
			}
		}

		return result as T;
	}

	/**
	 * Zod-like safe parsing. If `success` is true, `data` contains the parsed data. Otherwise `error` contains any parsing errors
	 *
	 * @param data - Raw binary data to parse with the current structure
	 * @returns An object containing either `success: true` and `data`, or `success: false` and `error`
	 */
	public safeParse(data: Buffer): { success: true; data: Prettify<T> } | { success: false; error: unknown } {
		try {
			return {
				success: true,
				data: this.parse(data)
			};
		} catch (error: unknown) {
			return {
				success: false,
				error: error
			};
		}
	}

	/**
	 * Uses the current structure to encode `parsed`. Will throw any errors that occur
	 *
	 * @param data - Object of parsed data to be coded
	 * @returns Encoded data
	 */
	public encode(parsed: Prettify<T>): Buffer {
		const out = Buffer.alloc(this.size());
		const stream = new BitStream(out, out.byteOffset, out.byteLength);
		const parsedKeys = Object.keys(parsed);
		let latestField: {
			name: string;
			value: unknown;
		} | undefined = undefined;

		stream.bigEndian = true; // * Make this match binary-parser, BE by default

		for (const command of this.commands) {
			if ('name' in command && !parsedKeys.includes(command.name)) {
				throw new Error(`Failed to find data for field ${command.name}`);
			}

			if (command.type === 'set_endianness') {
				stream.bigEndian = command.endianness === 'big' ? true : false;
			}

			if (command.type === 'skip') {
				stream.index += command.bits;
				continue;
			}

			if (command.type === 'custom_validate') {
				command.callback(parsed);
				continue;
			}

			if (command.type === 'check_min' && latestField) {
				if (latestField.value as number < command.value) {
					throw new Error(`Field '${latestField.name}' is invalid. Value ${latestField.value} is less than ${command.value}`);
				}

				continue;
			}

			if (command.type === 'check_max' && latestField) {
				if (latestField.value as number > command.value) {
					throw new Error(`Field '${latestField.name}' is invalid. Value ${latestField.value} is greater than ${command.value}`);
				}

				continue;
			}

			if (command.type === 'check_range' && latestField) {
				if (latestField.value as number < command.min) {
					throw new Error(`Field '${latestField.name}' is invalid. Value ${latestField.value} is less than ${command.min}`);
				}

				if (latestField.value as number > command.max) {
					throw new Error(`Field '${latestField.name}' is invalid. Value ${latestField.value} is greater than ${command.max}`);
				}

				continue;
			}

			if ('name' in command) {
				command.encode(stream, parsed);

				latestField = {
					name: command.name,
					value: (parsed as Record<string, unknown>)[command.name]
				};
			}
		}

		return out;
	}

	/**
	 * Zod-like safe encoding. If `success` is true, `data` contains the parsed data. Otherwise `error` contains any encoding errors
	 *
	 * @param parsed - Object of parsed data to be coded
	 * @returns An object containing either `success: true` and `data`, or `success: false` and `error`
	 */
	public safeEncode(parsed: Prettify<T>): { success: true; data: Buffer } | { success: false; error: unknown } {
		try {
			return {
				success: true,
				data: this.encode(parsed)
			};
		} catch (error) {
			return {
				success: false,
				error: error
			};
		}
	}

	/**
	 * Calculates the byte size based on the given structure
	 *
	 * @returns The number of bytes the structure requires
	 */
	public size(): number {
		let bits = 0;

		for (const command of this.commands) {
			if ('bits' in command) {
				bits += command.bits;
			}
		}

		return Math.ceil(bits / 8);
	}
}